### PR TITLE
Reducing bundle size

### PR DESCRIPTION
**Pull request by szilarddoro**
## General
By upgrading [js-yaml](https://github.com/nodeca/js-yaml) to the latest version `4.1.0`, we can significantly reduce the bundle size. According to [bundlephobia's](https://bundlephobia.com/package/front-matter@4.0.2) report, this means a 70.9% reduction in bundle size, as the latest version of `js-yaml` excludes `esprima` from its dependencies.

## Caveats
Since `js-yaml` has introduced several [breaking changes](https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md), upgrading to the new version would mean that `front-matter` should also introduce a breaking change and no longer accept an options object.

Another important note is that because of this upgrade, `js-types` is no longer included in `js-yaml`, but in a separate `js-yaml-js-types` package instead. This is the reason why `esprima` could be excluded from the dependencies in the first place. As a result of this, the complex and unsafe test case was removed, since `front-matter` would no longer support YAML files with this kind of content.

## Suggestion
An option could be introduced to dynamically decide whether to use `js-yaml-js-types` when parsing a file. This is definitely something to think about if both bundle size and a wide range of features are important.

Example:
```js
fm(`...content...`, { parseJsTypes: true })
```

## Issues
This PR could be a solution for https://github.com/jxson/front-matter/issues/79

### CODE REVIEW

**Comment by szilarddoro** [comment]
Additionally, here are the differences between the two `js-yaml` versions:
* [Bundlephobia: js-yaml@3.13.1](https://bundlephobia.com/package/js-yaml@3.13.1)
* [Bundlephobia: js-yaml@4.1.0](https://bundlephobia.com/package/js-yaml@4.1.0)

**Comment by Toxaris** [comment]
Instead of dropping the options object, could the js-yaml `schema` be made configurable to fix #78?

**Comment by szilarddoro** [comment]
Yes, I think it can safely be included in the options object. I'm going to look into this during the weekend.

**Comment by szilarddoro** [comment]
@Toxaris - What do you think about the latest changes?

I think it's the best if we let users of the library fully configure the underlying `parse` function.

**Pull request closed without merging**
