### PR TITLE
test: add typescript declaration test

### PR DESCRIPTION
**Pull request by tyankatsu0105**
re https://github.com/jxson/front-matter/issues/61#issuecomment-629298885

### CODE REVIEW

**Comment by tyankatsu0105** [comment]
@jxson @kubosho 
How about this?

**Comment by jxson** [comment]
Overall looks pretty good, `check-dts` seems like a nice tool.

A couple questions:
- In the `test/index.types.ts` file there are no assertions, is that common for positive `check-dts` tests?
- There are also calls to console.log in the file, usually calling loggers in tests is undesirable. Are these intentional? (note that running the tests locally I don't see any log output)

**Comment by tyankatsu0105** [comment]
@jxson 
>In the test/index.types.ts file there are no assertions, is that common for positive check-dts tests?

See: https://github.com/ai/nanoevents/blob/master/test/types.ts
check-dts tests with comments whether occurred types error.
(I want to use assert like jest or chai....)


>There are also calls to console.log in the file, usually calling loggers in tests is undesirable. Are these intentional? (note that running the tests locally I don't see any log output)

For avoiding [this ts error](https://www.typescriptlang.org/v2/tsconfig#noUnusedLocals).

**Comment by jxson** [comment]
Okay great,

I just merged #67 which changes the signature of the exported function to `fm(string, { allowUnsafe: false })`. Could you sync your PR with master and update the type definitions and the new tests to match?

**Comment by tyankatsu0105** [comment]
OK. I'll try ;)

**Comment by tyankatsu0105** [comment]
@jxson 
I added the type `options` to fm.
Also, I updated tests :)

**Comment by jxson** [comment]
Awesome, thanks for this. Sorry for the late reply, I had a long weekend of
no computers ;)

I'll merge and publish this later today...

**Comment by tyankatsu0105** [comment]
Take it easy 😄

**Comment by jxson** [comment]
Published as front-matter@4.0.1

**Pull request merged**
