### PR TITLE
Add `yaml` property to returned `content` object

### PR DESCRIPTION
**Pull request by aleung**

### CODE REVIEW

**Comment by jxson** [comment]
This is a good idea, thanks for contributing!

Can you change the name of the variable to something generic (maybe `frontmatter` or something )? I have plans to make it possible to plugin parsers so people can use whatever they like (toml, cson, etc.) so naming it `yaml` wont be appropriate in those cases.

I am not sure what is up with the failing browser tests, I just kicked it off again. Hopefully it was just a hiccup.

**Comment by aleung** [comment]
I'll update the name.

The browser test failure seems to be a problem in environment:

> zuul -- test/index.js
> Error:
> Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
> See the zuul wiki (https://github.com/defunctzombie/zuul/wiki/Cloud-testing) for info on how to setup cloud testing.

**Comment by jxson** [comment]
I'll look into the failing browser tests, thanks for the contribution!

**Comment by jxson** [comment]
Published as 2.1.0, sorry it took a while.

There is a security feature which makes the credentials unaccessible to pull requests that was causing the browser test failure. I added a check so that browser tests don't run on future PRs.

**Pull request merged**
